/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        orange: {
          100: "#FFF6F1",
          200: "#FFDBC8",
          300: "#FFAA7D",
          400: "#FF8340",
          500: "#FF5B04",
        },
        bluegreen: {
          100: "#F1F7F8",
          200: "#DAE5E7",
          300: "#86BBC7",
          400: "#06ABC2",
          500: "#0C7F8E",
          600: "#245E66",
          700: "#224F55",
          800: "#2E3D4F",
        },
        neutral: {
          0: "#FFFFFF",
          50: "#F6F8F8",
          100: "#F1F1F1",
          200: "#D3D3D3",
          300: "#9C9C9C",
          400: "#7D7D7D",
          500: "#566065",
          600: "#243037",
          1000: "#000000",
        },
        yellow: {
          100: "#FFF9ED",
          200: "#E29500",
        },
        red: {
          100: "#FE2E00",
        },
      },
      fontFamily: {
        "dm-sans": ['"DM Sans"', "sans-serif"],
        rasa: ['"Rasa"', "serif"],
      },
      fontSize: {
        "display-serif": "64px",
        "h1-serif": "54px",
        "h2-serif": "44px",
        "h2-serif-normal": "38px",
        "h3-serif-feature": "30px",
        "h3-serif": "26px",
        "h4-serif": "20px",
        "display-sans": "40px",
        "h1-sans": "28px",
        "h2-sans": "24px",
        "h3-sans": "20px",
        "h4-sans-uppercase": "18px",
        "h5-dashboard": "16px",
        "p18-bold": "18px",
        p18: "18px",
        "p16-bold": "16px",
        "p16-medium": "16px",
        p16: "16px",
        "p14-medium": "14px",
        "p14-uppercase": "14px",
        p14: "14px",
        "p12-medium": "12px",
        label16: "16px",
        link16: "16px",
        legend14: "14px",
      },
      fontWeight: {
        "display-serif": "700",
        "h1-serif": "700",
        "h2-serif": "600",
        "h2-serif-normal": "600",
        "h3-serif-feature": "600",
        "h3-serif": "600",
        "h4-serif": "600",
        "display-sans": "700",
        "h1-sans": "700",
        "h2-sans": "700",
        "h3-sans": "700",
        "h4-sans-uppercase": "400",
        "h5-dashboard": "500",
        "p18-bold": "700",
        p18: "400",
        "p16-bold": "700",
        "p16-medium": "500",
        p16: "400",
        "p14-medium": "500",
        "p14-uppercase": "400",
        p14: "400",
        "p12-medium": "500",
        label16: "400",
        link16: "400",
        legend14: "700",
      },
      lineHeight: {
        "display-serif": "110%",
        "h1-serif": "110%",
        "h2-serif": "auto",
        "h2-serif-normal": "auto",
        "h3-serif-feature": "auto",
        "h3-serif": "auto",
        "h4-serif": "auto",
        "display-sans": "auto",
        "h1-sans": "auto",
        "h2-sans": "auto",
        "h3-sans": "auto",
        "h4-sans-uppercase": "150%",
        "h5-dashboard": "auto",
        "p18-bold": "auto",
        p18: "auto",
        "p16-bold": "auto",
        "p16-medium": "auto",
        p16: "auto",
        "p14-medium": "auto",
        "p14-uppercase": "150%",
        p14: "auto",
        "p12-medium": "auto",
        label16: "auto",
        link16: "auto",
        legend14: "auto",
      },
    },
  },
  plugins: [
    // eslint-disable-next-line global-require
    require("@tailwindcss/container-queries"),
    function ({ addUtilities, theme, e }) {
      const newUtilities = {
        ".display-serif": {
          fontFamily: theme("fontFamily.rasa"),
          fontWeight: theme("fontWeight.display-serif"),
          fontSize: theme("fontSize.display-serif"),
          lineHeight: theme("lineHeight.display-serif"),
        },
        ".h1-serif": {
          fontFamily: theme("fontFamily.rasa"),
          fontWeight: theme("fontWeight.h1-serif"),
          fontSize: theme("fontSize.h1-serif"),
          lineHeight: theme("lineHeight.h1-serif"),
        },
        ".h2-serif": {
          fontFamily: theme("fontFamily.rasa"),
          fontWeight: theme("fontWeight.h2-serif"),
          fontSize: theme("fontSize.h2-serif"),
          lineHeight: theme("lineHeight.h2-serif"),
        },
        ".h2-serif-normal": {
          fontFamily: theme("fontFamily.rasa"),
          fontWeight: theme("fontWeight.h2-serif-normal"),
          fontSize: theme("fontSize.h2-serif-normal"),
          lineHeight: theme("lineHeight.h2-serif-normal"),
        },
        ".h3-serif-feature": {
          fontFamily: theme("fontFamily.rasa"),
          fontWeight: theme("fontWeight.h3-serif-feature"),
          fontSize: theme("fontSize.h3-serif-feature"),
          lineHeight: theme("lineHeight.h3-serif-feature"),
        },
        ".h3-serif": {
          fontFamily: theme("fontFamily.rasa"),
          fontWeight: theme("fontWeight.h3-serif"),
          fontSize: theme("fontSize.h3-serif"),
          lineHeight: theme("lineHeight.h3-serif"),
        },
        ".h4-serif": {
          fontFamily: theme("fontFamily.rasa"),
          fontWeight: theme("fontWeight.h4-serif"),
          fontSize: theme("fontSize.h4-serif"),
          lineHeight: theme("lineHeight.h4-serif"),
        },
        ".display-sans": {
          fontFamily: theme("fontFamily.dm-sans"),
          fontWeight: theme("fontWeight.display-sans"),
          fontSize: theme("fontSize.display-sans"),
          lineHeight: theme("lineHeight.display-sans"),
        },
        ".h1-sans": {
          fontFamily: theme("fontFamily.dm-sans"),
          fontWeight: theme("fontWeight.h1-sans"),
          fontSize: theme("fontSize.h1-sans"),
          lineHeight: theme("lineHeight.h1-sans"),
        },
        ".h2-sans": {
          fontFamily: theme("fontFamily.dm-sans"),
          fontWeight: theme("fontWeight.h2-sans"),
          fontSize: theme("fontSize.h2-sans"),
          lineHeight: theme("lineHeight.h2-sans"),
        },
        ".h3-sans": {
          fontFamily: theme("fontFamily.dm-sans"),
          fontWeight: theme("fontWeight.h3-sans"),
          fontSize: theme("fontSize.h3-sans"),
          lineHeight: theme("lineHeight.h3-sans"),
        },
        ".h4-sans-uppercase": {
          fontFamily: theme("fontFamily.dm-sans"),
          fontWeight: theme("fontWeight.h4-sans-uppercase"),
          fontSize: theme("fontSize.h4-sans-uppercase"),
          lineHeight: theme("lineHeight.h4-sans-uppercase"),
        },
        ".h5-dashboard": {
          fontFamily: theme("fontFamily.dm-sans"),
          fontWeight: theme("fontWeight.h5-dashboard"),
          fontSize: theme("fontSize.h5-dashboard"),
          lineHeight: theme("lineHeight.h5-dashboard"),
        },
        ".p18-bold": {
          fontFamily: theme("fontFamily.dm-sans"),
          fontWeight: theme("fontWeight.p18-bold"),
          fontSize: theme("fontSize.p18-bold"),
          lineHeight: theme("lineHeight.p18-bold"),
        },
        ".p18": {
          fontFamily: theme("fontFamily.dm-sans"),
          fontWeight: theme("fontWeight.p18"),
          fontSize: theme("fontSize.p18"),
          lineHeight: theme("lineHeight.p18"),
        },
        ".p16-bold": {
          fontFamily: theme("fontFamily.dm-sans"),
          fontWeight: theme("fontWeight.p16-bold"),
          fontSize: theme("fontSize.p16-bold"),
          lineHeight: theme("lineHeight.p16-bold"),
        },
        ".p16-medium": {
          fontFamily: theme("fontFamily.dm-sans"),
          fontWeight: theme("fontWeight.p16-medium"),
          fontSize: theme("fontSize.p16-medium"),
          lineHeight: theme("lineHeight.p16-medium"),
        },
        ".p16": {
          fontFamily: theme("fontFamily.dm-sans"),
          fontWeight: theme("fontWeight.p16"),
          fontSize: theme("fontSize.p16"),
          lineHeight: theme("lineHeight.p16"),
        },
        ".p14-medium": {
          fontFamily: theme("fontFamily.dm-sans"),
          fontWeight: theme("fontWeight.p14-medium"),
          fontSize: theme("fontSize.p14-medium"),
          lineHeight: theme("lineHeight.p14-medium"),
        },
        ".p14-uppercase": {
          fontFamily: theme("fontFamily.dm-sans"),
          fontWeight: theme("fontWeight.p14-uppercase"),
          fontSize: theme("fontSize.p14-uppercase"),
          lineHeight: theme("lineHeight.p14-uppercase"),
        },
        ".p14": {
          fontFamily: theme("fontFamily.dm-sans"),
          fontWeight: theme("fontWeight.p14"),
          fontSize: theme("fontSize.p14"),
          lineHeight: theme("lineHeight.p14"),
        },
        ".p12-medium": {
          fontFamily: theme("fontFamily.dm-sans"),
          fontWeight: theme("fontWeight.p12-medium"),
          fontSize: theme("fontSize.p12-medium"),
          lineHeight: theme("lineHeight.p12-medium"),
        },
        ".link16": {
          fontFamily: theme("fontFamily.dm-sans"),
          fontWeight: theme("fontWeight.link16"),
          fontSize: theme("fontSize.link16"),
          lineHeight: theme("lineHeight.link16"),
        },
        ".label16": {
          fontFamily: theme("fontFamily.dm-sans"),
          fontWeight: theme("fontWeight.label16"),
          fontSize: theme("fontSize.label16"),
          lineHeight: theme("lineHeight.label16"),
        },
        ".legend14": {
          fontFamily: theme("fontFamily.dm-sans"),
          fontWeight: theme("fontWeight.legend14"),
          fontSize: theme("fontSize.legend14"),
          lineHeight: theme("lineHeight.legend14"),
        },
      };
      addUtilities(newUtilities, ["responsive", "hover"]);
    },
  ],
};
